const messages = [
    "Your mental health is just as important as your physical health.",
    "It’s okay not to be okay.",
    "You are not your mental illness.",
    "Your struggles do not define you.",
    "Taking care of your mental health is an act of self-love.",
    "You are worthy of happiness and peace of mind.",
    "There is no shame in seeking help for your mental health.",
    "It’s okay to take a break and prioritize your mental health.",
    "You are not alone in your struggles.",
    "It’s okay to ask for support when you need it.",
    "Mental health is not a destination, it’s a journey.",
    "Your mental health matters more than any external validation.",
    "Healing is not linear, but it is possible.",
    "You are stronger than you realize.",
    "Your mental health journey is unique to you.",
    "Self-care is not selfish, it’s necessary for good mental health.",
    "Small steps can lead to big progress in mental health.",
    "You are capable of overcoming your mental health challenges.",
    "Mental illness is not a personal failure, it’s a medical condition.",
    "Your mental health should not be stigmatized.",
    "You are deserving of a life free from mental health struggles.",
    "Your mental health journey may be difficult, but it’s worth it.",
    "You are not weak for struggling with mental health issues.",
    "It’s okay to take medication for your mental health.",
    "You are not a burden for seeking help for your mental health.",
    "Mental health issues do not make you any less of a person.",
    "Your mental health is just as important as your career or education.",
    "You are capable of managing your mental health and living a fulfilling life.",
    "You have the power to overcome your mental health challenges.",
    "It’s okay to take time to focus on your mental health."
];

module.exports = messages;